#!/usr/bin/env python3
"""Build expanded dictionary from zomidaily new words.

Reads top 1000 new words from new_words.jsonl, checks against existing
dictionary, and creates dict_zomidaily_expanded.jsonl with morphological
analysis for unknown words.
"""

import json
import re
from pathlib import Path
from typing import Any

DATA_DIR = Path("/home/peter/Documents/Projects/zolai-ai/data")
NEW_WORDS_PATH = DATA_DIR / "raw/zomidaily/vocabulary/new_words.jsonl"
MASTER_DICT_PATH = DATA_DIR / "dictionary/processed/dict_zo_en_master_v1.jsonl"
OUTPUT_PATH = DATA_DIR / "dictionary/processed/dict_zomidaily_expanded.jsonl"
VERB_ROOTS = {
    "pai": "go",
    "mu": "see",
    "ne": "eat",
    "gen": "know",
    "bawl": "make",
    "ci": "say",
    "om": "exist/be",
    "hi": "be/exist",
    "pia": "give",
    "thu": "hear/listen",
    "hong": "come/arrive",
    "va": "return",
    "khia": "depart/leave",
    "lut": "enter",
    "kik": "return/go back",
    "dam": "live/be healthy",
    "khaw": "ask",
    "leh": "take/carry",
    "pi": "die/pass away",
    "si": "die",
    "in": "drink",
    "teng": "stand",
    "awl": "cook",
    "kha": "cross/pass",
    "kham": "be able",
    "lai": "write/read",
    "ngai": "think/consider",
    "nghet": "believe",
    "zong": "help",
    "pih": "arrive/reach",
    "ta": "begin/start",
}
NOUN_ROOTS = {
    "gam": "land/earth",
    "van": "sky/heaven",
    "tui": "water",
    "mi": "person",
    "numei": "woman",
    "khua": "village/place",
    "sing": "tree",
    "ni": "day/sun",
    "nu": "mother",
    "pa": "father",
    "tapa": "son/child",
    "lung": "heart/mind",
    "khat": "one",
    "nun": "eye",
    "law": "hand",
    "kheng": "head",
    "paht": "body",
    "kam": "word/speech",
    "tun": "road/path",
    "lai": "book/text",
    "tang": "story/history",
    "lei": "ground/land",
    "thu": "thing/matter",
    "hna": "work",
    "nasepna": "career",
    "biakna": "worship",
}
ADJ_ROOTS = {
    "dam": "healthy/well",
    "pi": "good",
    "kham": "able/strong",
    "nung": "long/far",
    "thuk": "deep",
    "hngal": "big/great",
    "than": "sharp/clever",
    "sang": "new",
    "zel": "old/aged",
    "kha": "cold",
    "tui": "hot",
    "kim": "correct/right",
    "mal": "wrong/bad",
}
PARTICLES = {
    "hi",
    "hen",
    "un",
    "in",
    "vo",
    "lo",
    "kei",
    "hiam",
    "leh",
    "tawh",
    "ah",
    "te",
    "pen",
    "na",
    "ki",
    "ci",
    "hong",
    "va",
    "khia",
    "lut",
    "kik",
    "ta",
    "zo",
    "khin",
    "lai",
    "ding",
    "ka",
    "a",
    "i",
    "kami",
    "nang",
    "amah",
    "mahmah",
    "uhhi",
    "ahihi",
    "cihi",
    "aki",
    "ii",
    "peuhmah",
    "ahihman",
}
KNOWN_TRANSLATIONS = {
    "mahmah": ("very/greatly", "adverb", "intensifier"),
    "uhhi": ("[emphasis particle]", "particle", "grammar"),
    "ahihi": ("[discourse marker]", "particle", "grammar"),
    "malaysia": ("Malaysia", "proper noun", "place"),
    "ii": ("[emphasis particle]", "particle", "grammar"),
    "thupi": ("news/report", "noun", "media"),
    "tedim": ("Tedim", "proper noun", "place"),
    "zomite": ("Zomi people", "noun", "community"),
    "aki": ("[emphatic particle]", "particle", "grammar"),
    "cihi": ("[sentence-final particle]", "particle", "grammar"),
    "rm": ("Ringgit (Malaysian currency)", "noun", "unit"),
    "usa": ("USA", "proper noun", "place"),
    "dr": ("doctor", "title", "professional"),
    "ahihman": ("because", "conjunction", "grammar"),
    "peuhmah": ("also/too", "adverb", "grammar"),
    "pm": ("Prime Minister", "title", "political"),
    "unhcr": ("UNHCR", "noun", "organization"),
    "jesu": ("Jesus", "proper noun", "religion"),
    "inzong": ("inside/within", "adverb", "location"),
    "tepen": ("today", "adverb", "temporal"),
    "napi": ("yesterday", "adverb", "temporal"),
    "abeisa": ("day before yesterday", "adverb", "temporal"),
    "mah": ("[particle]", "particle", "grammar"),
    "ci": ("say", "verb", "communication"),
    "pen": ("is/are (copula)", "verb", "grammar"),
    "leh": ("and/with", "conjunction", "grammar"),
    "tawh": ("together/with", "adverb", "accompaniment"),
    "khat": ("one", "number", "numeral"),
    "ah": ("[particle]", "particle", "grammar"),
    "te": ("[topic marker]", "particle", "grammar"),
    "tua": ("that", "pronoun", "grammar"),
    "ki": ("[reflexive/plural marker]", "particle", "grammar"),
    "na": ("[possessive/noun marker]", "particle", "grammar"),
    "om": ("exist/be", "verb", "existence"),
    "in": ("[ergative marker]", "particle", "grammar"),
    "lo": ("[negation particle]", "particle", "grammar"),
    "hi": ("[declarative particle]", "particle", "grammar"),
    "ding": ("[future marker]", "particle", "grammar"),
    "hong": ("come/arrive", "verb", "motion"),
    "va": ("return", "verb", "motion"),
    "khia": ("depart/leave", "verb", "motion"),
    "lut": ("enter", "verb", "motion"),
    "kik": ("return/go back", "verb", "motion"),
    "ta": ("begin/start", "verb", "aspect"),
    "zo": ("finish/completive", "verb", "aspect"),
    "khin": ("experiential (have done)", "verb", "aspect"),
    "lai": ("progressive (is doing)", "verb", "aspect"),
    "ka": ("I/me (1st person)", "pronoun", "grammar"),
    "a": ("he/his (3rd person agreement)", "pronoun", "grammar"),
    "i": ("he/him (3rd person)", "pronoun", "grammar"),
    "nang": ("you (2nd person)", "pronoun", "grammar"),
    "amah": ("he himself (emphatic)", "pronoun", "grammar"),
    "kami": ("we/us (inclusive)", "pronoun", "grammar"),
    "ngai": ("I/me (emphatic)", "pronoun", "grammar"),
    "kei": ("[negation for all persons]", "particle", "grammar"),
    "hiam": ("[question marker]", "particle", "grammar"),
    "vo": ("[exclamatory particle]", "particle", "grammar"),
    "hen": ("[polite particle]", "particle", "grammar"),
    "un": ("[request/polite marker]", "particle", "grammar"),
    "covid": ("COVID", "noun", "health"),
    "vaccine": ("vaccine", "noun", "health"),
    "facebook": ("Facebook", "noun", "technology"),
    "online": ("online", "adjective", "technology"),
    "digital": ("digital", "adjective", "technology"),
    "computer": ("computer", "noun", "technology"),
    "internet": ("internet", "noun", "technology"),
    "smartphone": ("smartphone", "noun", "technology"),
    "whatsapp": ("WhatsApp", "noun", "technology"),
    "youtube": ("YouTube", "noun", "technology"),
    "telegram": ("Telegram", "noun", "technology"),
    "covid19": ("COVID-19", "noun", "health"),
    "pfizer": ("Pfizer", "proper noun", "health"),
    "moderna": ("Moderna", "proper noun", "health"),
    "astrazeneca": ("AstraZeneca", "proper noun", "health"),
    "sinovac": ("Sinovac", "proper noun", "health"),
    "yangon": ("Yangon", "proper noun", "place"),
    "hoihtak": ("celebration/festival", "noun", "community"),
    "uhi": ("[emphasis particle]", "particle", "grammar"),
    "akipan": ("all/everyone", "pronoun", "grammar"),
    "zya": ("money/cost", "noun", "economy"),
    "tg": ("Telegram", "noun", "technology"),
    "uha": ("[particle]", "particle", "grammar"),
    "tulaitak": ("development/progress", "noun", "abstract"),
    "paite": ("Paite people", "noun", "community"),
    "falam": ("Falam", "proper noun", "place"),
    "hakha": ("Hakha", "proper noun", "place"),
    "churachandpur": ("Churachandpur", "proper noun", "place"),
    "mizoram": ("Mizoram", "proper noun", "place"),
    "manipur": ("Manipur", "proper noun", "place"),
    "myanmar": ("Myanmar", "proper noun", "place"),
    "india": ("India", "proper noun", "place"),
    "bangladesh": ("Bangladesh", "proper noun", "place"),
    "nepal": ("Nepal", "proper noun", "place"),
    "corona": ("coronavirus", "noun", "health"),
    "program": ("program", "noun", "technology"),
    "app": ("application", "noun", "technology"),
    "wifi": ("WiFi", "noun", "technology"),
    "battery": ("battery", "noun", "technology"),
    "camera": ("camera", "noun", "technology"),
    "photo": ("photo", "noun", "technology"),
    "video": ("video", "noun", "technology"),
    "music": ("music", "noun", "art"),
    "movie": ("movie", "noun", "art"),
    "song": ("song", "noun", "art"),
    "dance": ("dance", "verb", "art"),
    "art": ("art", "noun", "art"),
    "painting": ("painting", "noun", "art"),
    "drawing": ("drawing", "noun", "art"),
    "poem": ("poem", "noun", "art"),
    "story": ("story", "noun", "art"),
    "novel": ("novel", "noun", "art"),
    "book": ("book", "noun", "education"),
    "school": ("school", "noun", "education"),
    "teacher": ("teacher", "noun", "education"),
    "student": ("student", "noun", "education"),
    "class": ("class", "noun", "education"),
    "exam": ("exam", "noun", "education"),
    "grade": ("grade", "verb", "furniture"),
    "university": ("university", "noun", "education"),
    "college": ("college", "noun", "education"),
    "degree": ("degree", "noun", "education"),
    "diploma": ("diploma", "noun", "education"),
    "scholarship": ("scholarship", "noun", "education"),
    "research": ("research", "noun", "education"),
    "library": ("library", "noun", "education"),
    "newspaper": ("newspaper", "noun", "media"),
    "magazine": ("magazine", "noun", "media"),
    "journal": ("journal", "noun", "media"),
    "article": ("article", "noun", "media"),
    "report": ("report", "noun", "media"),
    "document": ("document", "verb", "furniture"),
    "letter": ("letter", "noun", "communication"),
    "email": ("email", "noun", "communication"),
    "message": ("message", "noun", "communication"),
    "call": ("call", "verb", "furniture"),
    "phone": ("phone", "noun", "communication"),
    "radio": ("radio", "noun", "communication"),
    "television": ("television", "noun", "communication"),
    "station": ("station", "verb", "furniture"),
    "bus": ("bus", "noun", "transport"),
    "car": ("car", "noun", "transport"),
    "train": ("train", "verb", "furniture"),
    "airport": ("airport", "noun", "transport"),
    "plane": ("plane", "noun", "transport"),
    "boat": ("boat", "noun", "transport"),
    "road": ("road", "noun", "transport"),
    "bridge": ("bridge", "noun", "transport"),
    "house": ("house", "verb", "furniture"),
    "building": ("building", "noun", "housing"),
    "apartment": ("apartment", "noun", "housing"),
    "hotel": ("hotel", "noun", "housing"),
    "restaurant": ("restaurant", "noun", "food"),
    "cafe": ("cafe", "noun", "food"),
    "shop": ("shop", "noun", "economy"),
    "store": ("store", "verb", "furniture"),
    "market": ("market", "noun", "economy"),
    "price": ("price", "noun", "economy"),
    "cost": ("cost", "noun", "economy"),
    "money": ("money", "noun", "economy"),
    "bank": ("bank", "noun", "economy"),
    "account": ("account", "noun", "furniture"),
    "salary": ("salary", "noun", "economy"),
    "tax": ("tax", "noun", "economy"),
    "income": ("income", "noun", "economy"),
    "expense": ("expense", "noun", "economy"),
    "profit": ("profit", "noun", "economy"),
    "loss": ("loss", "noun", "economy"),
    "business": ("business", "noun", "economy"),
    "company": ("company", "noun", "economy"),
    "factory": ("factory", "noun", "economy"),
    "industry": ("industry", "noun", "economy"),
    "agriculture": ("agriculture", "noun", "economy"),
    "farm": ("farm", "noun", "economy"),
    "rice": ("rice", "noun", "food"),
    "vegetable": ("vegetable", "noun", "food"),
    "fruit": ("fruit", "noun", "food"),
    "meat": ("meat", "noun", "food"),
    "fish": ("fish", "noun", "food"),
    "egg": ("egg", "noun", "food"),
    "milk": ("milk", "noun", "food"),
    "bread": ("bread", "noun", "food"),
    "sugar": ("sugar", "noun", "food"),
    "salt": ("salt", "noun", "food"),
    "oil": ("oil", "noun", "food"),
    "spice": ("spice", "noun", "food"),
    "tea": ("tea", "noun", "food"),
    "coffee": ("coffee", "noun", "food"),
    "water": ("water", "noun", "nature"),
    "rain": ("rain", "noun", "nature"),
    "sun": ("sun", "noun", "nature"),
    "moon": ("moon", "noun", "nature"),
    "star": ("star", "noun", "nature"),
    "sky": ("sky", "noun", "nature"),
    "earth": ("earth", "noun", "nature"),
    "mountain": ("mountain", "noun", "nature"),
    "river": ("river", "noun", "nature"),
    "lake": ("lake", "noun", "nature"),
    "forest": ("forest", "noun", "nature"),
    "tree": ("tree", "noun", "nature"),
    "flower": ("flower", "noun", "nature"),
    "animal": ("animal", "noun", "nature"),
    "bird": ("bird", "noun", "nature"),
    "dog": ("dog", "noun", "nature"),
    "cat": ("cat", "noun", "nature"),
    "horse": ("horse", "noun", "nature"),
    "cow": ("cow", "noun", "nature"),
    "chicken": ("chicken", "noun", "nature"),
    "pig": ("pig", "noun", "nature"),
    "weather": ("weather", "noun", "nature"),
    "climate": ("climate", "noun", "nature"),
    "temperature": ("temperature", "noun", "nature"),
    "season": ("season", "noun", "nature"),
    "spring": ("spring", "verb", "furniture"),
    "summer": ("summer", "noun", "nature"),
    "autumn": ("autumn", "noun", "nature"),
    "winter": ("winter", "noun", "nature"),
    "doctor": ("doctor", "noun", "health"),
    "hospital": ("hospital", "noun", "health"),
    "medicine": ("medicine", "noun", "health"),
    "pill": ("pill", "noun", "health"),
    "disease": ("disease", "noun", "health"),
    "illness": ("illness", "noun", "health"),
    "fever": ("fever", "noun", "health"),
    "pain": ("pain", "noun", "health"),
    "injury": ("injury", "noun", "health"),
    "wound": ("wound", "verb", "furniture"),
    "blood": ("blood", "noun", "health"),
    "heart": ("heart", "noun", "health"),
    "lung": ("lung", "noun", "health"),
    "brain": ("brain", "noun", "health"),
    "eye": ("eye", "noun", "health"),
    "ear": ("ear", "noun", "health"),
    "nose": ("nose", "noun", "health"),
    "mouth": ("mouth", "noun", "health"),
    "tooth": ("tooth", "noun", "health"),
    "tongue": ("tongue", "noun", "health"),
    "skin": ("skin", "verb", "furniture"),
    "bone": ("bone", "noun", "health"),
    "muscle": ("muscle", "noun", "health"),
    "joint": ("joint", "noun", "health"),
    "finger": ("finger", "noun", "health"),
    "toe": ("toe", "noun", "health"),
    "leg": ("leg", "noun", "health"),
    "arm": ("arm", "verb", "furniture"),
    "head": ("head", "noun", "health"),
    "face": ("face", "noun", "health"),
    "neck": ("neck", "noun", "health"),
    "back": ("back", "verb", "furniture"),
    "stomach": ("stomach", "noun", "health"),
    "waist": ("waist", "noun", "health"),
    "hip": ("hip", "noun", "health"),
    "shoulder": ("shoulder", "noun", "health"),
    "knee": ("knee", "noun", "health"),
    "ankle": ("ankle", "noun", "health"),
    "foot": ("foot", "noun", "health"),
    "shoe": ("shoe", "noun", "clothing"),
    "shirt": ("shirt", "noun", "clothing"),
    "pants": ("pants", "noun", "clothing"),
    "dress": ("dress", "noun", "clothing"),
    "hat": ("hat", "noun", "clothing"),
    "jacket": ("jacket", "noun", "clothing"),
    "coat": ("coat", "noun", "clothing"),
    "sock": ("sock", "noun", "clothing"),
    "belt": ("belt", "noun", "clothing"),
    "bag": ("bag", "noun", "clothing"),
    "wallet": ("wallet", "noun", "clothing"),
    "watch": ("watch", "verb", "furniture"),
    "ring": ("ring", "verb", "furniture"),
    "necklace": ("necklace", "noun", "accessory"),
    "bracelet": ("bracelet", "noun", "accessory"),
    "glasses": ("glasses", "noun", "accessory"),
    "umbrella": ("umbrella", "noun", "accessory"),
    "knife": ("knife", "noun", "tool"),
    "fork": ("fork", "noun", "tool"),
    "spoon": ("spoon", "noun", "tool"),
    "plate": ("plate", "noun", "tool"),
    "bowl": ("bowl", "noun", "tool"),
    "cup": ("cup", "noun", "tool"),
    "glass": ("glass", "noun", "tool"),
    "bottle": ("bottle", "noun", "tool"),
    "pot": ("pot", "noun", "tool"),
    "pan": ("pan", "noun", "tool"),
    "stove": ("stove", "noun", "tool"),
    "oven": ("oven", "noun", "tool"),
    "refrigerator": ("refrigerator", "noun", "tool"),
    "freezer": ("freezer", "noun", "tool"),
    "washing": ("washing", "noun", "tool"),
    "machine": ("machine", "noun", "tool"),
    "hammer": ("hammer", "noun", "tool"),
    "saw": ("saw", "verb", "furniture"),
    "drill": ("drill", "noun", "tool"),
    "screwdriver": ("screwdriver", "noun", "tool"),
    "plank": ("plank", "noun", "tool"),
    "nail": ("nail", "noun", "tool"),
    "screw": ("screw", "noun", "tool"),
    "rope": ("rope", "noun", "tool"),
    "wire": ("wire", "noun", "furniture"),
    "cable": ("cable", "noun", "furniture"),
    "pipe": ("pipe", "noun", "tool"),
    "tap": ("tap", "verb", "furniture"),
    "drain": ("drain", "noun", "tool"),
    "toilet": ("toilet", "noun", "facility"),
    "bathroom": ("bathroom", "noun", "facility"),
    "kitchen": ("kitchen", "noun", "facility"),
    "bedroom": ("bedroom", "noun", "facility"),
    "living": ("living", "noun", "facility"),
    "room": ("room", "noun", "facility"),
    "dining": ("dining", "noun", "facility"),
    "garden": ("garden", "noun", "facility"),
    "yard": ("yard", "noun", "facility"),
    "fence": ("fence", "noun", "facility"),
    "gate": ("gate", "noun", "facility"),
    "door": ("door", "noun", "facility"),
    "window": ("window", "noun", "facility"),
    "floor": ("floor", "noun", "facility"),
    "wall": ("wall", "noun", "facility"),
    "ceiling": ("ceiling", "noun", "facility"),
    "roof": ("roof", "noun", "facility"),
    "stair": ("stair", "noun", "facility"),
    "elevator": ("elevator", "noun", "facility"),
    "escalator": ("escalator", "noun", "facility"),
    "parking": ("parking", "noun", "facility"),
    "garage": ("garage", "noun", "facility"),
    "basement": ("basement", "noun", "facility"),
    "attic": ("attic", "noun", "facility"),
    "cabinet": ("cabinet", "noun", "furniture"),
    "chair": ("chair", "noun", "furniture"),
    "table": ("table", "noun", "furniture"),
    "desk": ("desk", "noun", "furniture"),
    "bed": ("bed", "noun", "furniture"),
    "sofa": ("sofa", "noun", "furniture"),
    "couch": ("couch", "noun", "furniture"),
    "shelf": ("shelf", "noun", "furniture"),
    "drawer": ("drawer", "noun", "furniture"),
    "lamp": ("lamp", "noun", "furniture"),
    "light": ("light", "verb", "furniture"),
    "switch": ("switch", "noun", "furniture"),
    "socket": ("socket", "noun", "furniture"),
    "plug": ("plug", "noun", "furniture"),
    "remote": ("remote", "noun", "furniture"),
    "control": ("control", "verb", "furniture"),
    "button": ("button", "noun", "furniture"),
    "screen": ("screen", "noun", "furniture"),
    "display": ("display", "verb", "furniture"),
    "monitor": ("monitor", "verb", "furniture"),
    "keyboard": ("keyboard", "noun", "furniture"),
    "mouse": ("mouse", "noun", "furniture"),
    "printer": ("printer", "noun", "furniture"),
    "scanner": ("scanner", "noun", "furniture"),
    "copier": ("copier", "noun", "furniture"),
    "fax": ("fax", "noun", "furniture"),
    "router": ("router", "noun", "furniture"),
    "modem": ("modem", "noun", "furniture"),
    "server": ("server", "noun", "furniture"),
    "network": ("network", "noun", "furniture"),
    "connection": ("connection", "noun", "furniture"),
    "signal": ("signal", "noun", "furniture"),
    "password": ("password", "noun", "furniture"),
    "username": ("username", "noun", "furniture"),
    "profile": ("profile", "noun", "furniture"),
    "post": ("post", "noun", "furniture"),
    "comment": ("comment", "noun", "furniture"),
    "share": ("share", "verb", "furniture"),
    "like": ("like", "verb", "furniture"),
    "follow": ("follow", "verb", "furniture"),
    "subscribe": ("subscribe", "verb", "furniture"),
    "upload": ("upload", "verb", "furniture"),
    "download": ("download", "verb", "furniture"),
    "stream": ("stream", "verb", "furniture"),
    "play": ("play", "verb", "furniture"),
    "pause": ("pause", "verb", "furniture"),
    "stop": ("stop", "verb", "furniture"),
    "start": ("start", "verb", "furniture"),
    "begin": ("begin", "verb", "furniture"),
    "end": ("end", "verb", "furniture"),
    "finish": ("finish", "verb", "furniture"),
    "complete": ("complete", "verb", "furniture"),
    "save": ("save", "verb", "furniture"),
    "delete": ("delete", "verb", "furniture"),
    "edit": ("edit", "verb", "furniture"),
    "copy": ("copy", "verb", "furniture"),
    "paste": ("paste", "verb", "furniture"),
    "cut": ("cut", "verb", "furniture"),
    "undo": ("undo", "verb", "furniture"),
    "redo": ("redo", "verb", "furniture"),
    "refresh": ("refresh", "verb", "furniture"),
    "reload": ("reload", "verb", "furniture"),
    "open": ("open", "verb", "furniture"),
    "close": ("close", "verb", "furniture"),
    "minimize": ("minimize", "verb", "furniture"),
    "maximize": ("maximize", "verb", "furniture"),
    "resize": ("resize", "verb", "furniture"),
    "move": ("move", "verb", "furniture"),
    "drag": ("drag", "verb", "furniture"),
    "drop": ("drop", "verb", "furniture"),
    "click": ("click", "verb", "furniture"),
    "swipe": ("swipe", "verb", "furniture"),
    "scroll": ("scroll", "verb", "furniture"),
    "zoom": ("zoom", "verb", "furniture"),
    "rotate": ("rotate", "verb", "furniture"),
    "flip": ("flip", "verb", "furniture"),
    "turn": ("turn", "verb", "furniture"),
    "spin": ("spin", "verb", "furniture"),
    "shake": ("shake", "verb", "furniture"),
    "vibrate": ("vibrate", "verb", "furniture"),
    "buzz": ("buzz", "verb", "furniture"),
    "beep": ("beep", "verb", "furniture"),
    "flash": ("flash", "verb", "furniture"),
    "blink": ("blink", "verb", "furniture"),
    "glow": ("glow", "verb", "furniture"),
    "shine": ("shine", "verb", "furniture"),
    "fade": ("fade", "verb", "furniture"),
    "darken": ("darken", "verb", "furniture"),
    "brighten": ("brighten", "verb", "furniture"),
    "lighten": ("lighten", "verb", "furniture"),
    "dim": ("dim", "verb", "furniture"),
    "increase": ("increase", "verb", "furniture"),
    "decrease": ("decrease", "verb", "furniture"),
    "raise": ("raise", "verb", "furniture"),
    "lower": ("lower", "verb", "furniture"),
    "lift": ("lift", "verb", "furniture"),
    "push": ("push", "verb", "furniture"),
    "pull": ("pull", "verb", "furniture"),
    "press": ("press", "verb", "furniture"),
    "squeeze": ("squeeze", "verb", "furniture"),
    "stretch": ("stretch", "verb", "furniture"),
    "bend": ("bend", "verb", "furniture"),
    "fold": ("fold", "verb", "furniture"),
    "unfold": ("unfold", "verb", "furniture"),
    "roll": ("roll", "verb", "furniture"),
    "unroll": ("unroll", "verb", "furniture"),
    "wrap": ("wrap", "verb", "furniture"),
    "unwrap": ("unwrap", "verb", "furniture"),
    "tie": ("tie", "verb", "furniture"),
    "untie": ("untie", "verb", "furniture"),
    "knot": ("knot", "verb", "furniture"),
    "loosen": ("loosen", "verb", "furniture"),
    "tighten": ("tighten", "verb", "furniture"),
    "fasten": ("fasten", "verb", "furniture"),
    "unfasten": ("unfasten", "verb", "furniture"),
    "secure": ("secure", "verb", "furniture"),
    "release": ("release", "verb", "furniture"),
    "lock": ("lock", "verb", "furniture"),
    "unlock": ("unlock", "verb", "furniture"),
    "seal": ("seal", "verb", "furniture"),
    "unseal": ("unseal", "verb", "furniture"),
    "shut": ("shut", "verb", "furniture"),
    "block": ("block", "verb", "furniture"),
    "unblock": ("unblock", "verb", "furniture"),
    "obstruct": ("obstruct", "verb", "furniture"),
    "clear": ("clear", "verb", "furniture"),
    "remove": ("remove", "verb", "furniture"),
    "add": ("add", "verb", "furniture"),
    "insert": ("insert", "verb", "furniture"),
    "extract": ("extract", "verb", "furniture"),
    "shove": ("shove", "verb", "furniture"),
    "thrust": ("thrust", "verb", "furniture"),
    "stab": ("stab", "verb", "furniture"),
    "poke": ("poke", "verb", "furniture"),
    "prod": ("prod", "verb", "furniture"),
    "nudge": ("nudge", "verb", "furniture"),
    "bump": ("bump", "verb", "furniture"),
    "knock": ("knock", "verb", "furniture"),
    "hit": ("hit", "verb", "furniture"),
    "strike": ("strike", "verb", "furniture"),
    "slap": ("slap", "verb", "furniture"),
    "punch": ("punch", "verb", "furniture"),
    "kick": ("kick", "verb", "furniture"),
    "stomp": ("stomp", "verb", "furniture"),
    "step": ("step", "verb", "furniture"),
    "walk": ("walk", "verb", "furniture"),
    "run": ("run", "verb", "furniture"),
    "jump": ("jump", "verb", "furniture"),
    "hop": ("hop", "verb", "furniture"),
    "skip": ("skip", "verb", "furniture"),
    "leap": ("leap", "verb", "furniture"),
    "bound": ("bound", "verb", "furniture"),
    "bounce": ("bounce", "verb", "furniture"),
    "rebound": ("rebound", "verb", "furniture"),
    "reflect": ("reflect", "verb", "furniture"),
    "echo": ("echo", "verb", "furniture"),
    "resound": ("resound", "verb", "furniture"),
    "reverberate": ("reverberate", "verb", "furniture"),
    "tremble": ("tremble", "verb", "furniture"),
    "quiver": ("quiver", "verb", "furniture"),
    "shiver": ("shiver", "verb", "furniture"),
    "shudder": ("shudder", "verb", "furniture"),
    "flinch": ("flinch", "verb", "furniture"),
    "wince": ("wince", "verb", "furniture"),
    "cringe": ("cringe", "verb", "furniture"),
    "shrug": ("shrug", "verb", "furniture"),
    "nod": ("nod", "verb", "furniture"),
    "bow": ("bow", "verb", "furniture"),
    "kneel": ("kneel", "verb", "furniture"),
    "squat": ("squat", "verb", "furniture"),
    "crouch": ("crouch", "verb", "furniture"),
    "hunch": ("hunch", "verb", "furniture"),
    "lean": ("lean", "verb", "furniture"),
    "tilt": ("tilt", "verb", "furniture"),
    "slant": ("slant", "verb", "furniture"),
    "slope": ("slope", "verb", "furniture"),
    "incline": ("incline", "verb", "furniture"),
    "decline": ("decline", "verb", "furniture"),
    "descend": ("descend", "verb", "furniture"),
    "ascend": ("ascend", "verb", "furniture"),
    "climb": ("climb", "verb", "furniture"),
    "scale": ("scale", "verb", "furniture"),
    "mount": ("mount", "verb", "furniture"),
    "dismount": ("dismount", "verb", "furniture"),
    "alight": ("alight", "verb", "furniture"),
    "land": ("land", "verb", "furniture"),
    "take": ("take", "verb", "furniture"),
    "off": ("off", "verb", "furniture"),
    "board": ("board", "verb", "furniture"),
    "embark": ("embark", "verb", "furniture"),
    "disembark": ("disembark", "verb", "furniture"),
    "depart": ("depart", "verb", "furniture"),
    "arrive": ("arrive", "verb", "furniture"),
    "return": ("return", "verb", "furniture"),
    "come": ("come", "verb", "furniture"),
    "go": ("go", "verb", "furniture"),
    "travel": ("travel", "verb", "furniture"),
    "journey": ("journey", "verb", "furniture"),
    "voyage": ("voyage", "verb", "furniture"),
    "sail": ("sail", "verb", "furniture"),
    "fly": ("fly", "verb", "furniture"),
    "drive": ("drive", "verb", "furniture"),
    "ride": ("ride", "verb", "furniture"),
    "pedal": ("pedal", "verb", "furniture"),
    "row": ("row", "verb", "furniture"),
    "paddle": ("paddle", "verb", "furniture"),
    "swim": ("swim", "verb", "furniture"),
    "dive": ("dive", "verb", "furniture"),
    "surf": ("surf", "verb", "furniture"),
    "ski": ("ski", "verb", "furniture"),
    "skate": ("skate", "verb", "furniture"),
    "slide": ("slide", "verb", "furniture"),
    "glide": ("glide", "verb", "furniture"),
    "float": ("float", "verb", "furniture"),
    "sink": ("sink", "verb", "furniture"),
    "drown": ("drown", "verb", "furniture"),
    "submerge": ("submerge", "verb", "furniture"),
    "emerge": ("emerge", "verb", "furniture"),
    "appear": ("appear", "verb", "furniture"),
    "disappear": ("disappear", "verb", "furniture"),
    "vanish": ("vanish", "verb", "furniture"),
    "wither": ("wither", "verb", "furniture"),
    "shrivel": ("shrivel", "verb", "furniture"),
    "wilt": ("wilt", "verb", "furniture"),
    "droop": ("droop", "verb", "furniture"),
    "hang": ("hang", "verb", "furniture"),
    "dangle": ("dangle", "verb", "furniture"),
    "swing": ("swing", "verb", "furniture"),
    "sway": ("sway", "verb", "furniture"),
    "rock": ("rock", "verb", "furniture"),
    "tumble": ("tumble", "verb", "furniture"),
    "fall": ("fall", "verb", "furniture"),
    "plummet": ("plummet", "verb", "furniture"),
    "plunge": ("plunge", "verb", "furniture"),
    "crash": ("crash", "verb", "furniture"),
    "smash": ("smash", "verb", "furniture"),
    "shatter": ("shatter", "verb", "furniture"),
    "break": ("break", "verb", "furniture"),
    "snap": ("snap", "verb", "furniture"),
    "crack": ("crack", "verb", "furniture"),
    "split": ("split", "verb", "furniture"),
    "tear": ("tear", "verb", "furniture"),
    "rip": ("rip", "verb", "furniture"),
    "slice": ("slice", "verb", "furniture"),
    "chop": ("chop", "verb", "furniture"),
    "hack": ("hack", "verb", "furniture"),
    "hew": ("hew", "verb", "furniture"),
    "carve": ("carve", "verb", "furniture"),
    "sculpt": ("sculpt", "verb", "furniture"),
    "shape": ("shape", "verb", "furniture"),
    "mold": ("mold", "verb", "furniture"),
    "form": ("form", "verb", "furniture"),
    "fashion": ("fashion", "verb", "furniture"),
    "create": ("create", "verb", "furniture"),
    "make": ("make", "verb", "furniture"),
    "build": ("build", "verb", "furniture"),
    "construct": ("construct", "verb", "furniture"),
    "assemble": ("assemble", "verb", "furniture"),
    "disassemble": ("disassemble", "verb", "furniture"),
    "dismantle": ("dismantle", "verb", "furniture"),
    "demolish": ("demolish", "verb", "furniture"),
    "destroy": ("destroy", "verb", "furniture"),
    "ruin": ("ruin", "verb", "furniture"),
    "damage": ("damage", "verb", "furniture"),
    "harm": ("harm", "verb", "furniture"),
    "hurt": ("hurt", "verb", "furniture"),
    "injure": ("injure", "verb", "furniture"),
    "kill": ("kill", "verb", "furniture"),
    "murder": ("murder", "verb", "furniture"),
    "assassinate": ("assassinate", "verb", "furniture"),
    "execute": ("execute", "verb", "furniture"),
    "slaughter": ("slaughter", "verb", "furniture"),
    "butcher": ("butcher", "verb", "furniture"),
    "flay": ("flay", "verb", "furniture"),
    "peel": ("peel", "verb", "furniture"),
    "strip": ("strip", "verb", "furniture"),
    "bare": ("bare", "verb", "furniture"),
    "expose": ("expose", "verb", "furniture"),
    "reveal": ("reveal", "verb", "furniture"),
    "uncover": ("uncover", "verb", "furniture"),
    "discover": ("discover", "verb", "furniture"),
    "find": ("find", "verb", "furniture"),
    "lose": ("lose", "verb", "furniture"),
    "miss": ("miss", "verb", "furniture"),
    "search": ("search", "verb", "furniture"),
    "look": ("look", "verb", "furniture"),
    "see": ("see", "verb", "furniture"),
    "observe": ("observe", "verb", "furniture"),
    "notice": ("notice", "verb", "furniture"),
    "note": ("note", "verb", "furniture"),
    "mark": ("mark", "verb", "furniture"),
    "tag": ("tag", "verb", "furniture"),
    "label": ("label", "verb", "furniture"),
    "name": ("name", "verb", "furniture"),
    "address": ("address", "verb", "furniture"),
    "greet": ("greet", "verb", "furniture"),
    "welcome": ("welcome", "verb", "furniture"),
    "salute": ("salute", "verb", "furniture"),
    "honor": ("honor", "verb", "furniture"),
    "respect": ("respect", "verb", "furniture"),
    "admire": ("admire", "verb", "furniture"),
    "praise": ("praise", "verb", "furniture"),
    "compliment": ("compliment", "verb", "furniture"),
    "flatter": ("flatter", "verb", "furniture"),
    "criticize": ("criticize", "verb", "furniture"),
    "blame": ("blame", "verb", "furniture"),
    "accuse": ("accuse", "verb", "furniture"),
    "charge": ("charge", "verb", "furniture"),
    "sue": ("sue", "verb", "furniture"),
    "prosecute": ("prosecute", "verb", "furniture"),
    "defend": ("defend", "verb", "furniture"),
    "protect": ("protect", "verb", "furniture"),
    "guard": ("guard", "verb", "furniture"),
    "survey": ("survey", "verb", "furniture"),
    "inspect": ("inspect", "verb", "furniture"),
    "examine": ("examine", "verb", "furniture"),
    "analyze": ("analyze", "verb", "furniture"),
    "study": ("study", "verb", "furniture"),
    "learn": ("learn", "verb", "furniture"),
    "teach": ("teach", "verb", "furniture"),
    "instruct": ("instruct", "verb", "furniture"),
    "educate": ("educate", "verb", "furniture"),
    "coach": ("coach", "verb", "furniture"),
    "mentor": ("mentor", "verb", "furniture"),
    "guide": ("guide", "verb", "furniture"),
    "lead": ("lead", "verb", "furniture"),
    "direct": ("direct", "verb", "furniture"),
    "manage": ("manage", "verb", "furniture"),
    "operate": ("operate", "verb", "furniture"),
    "handle": ("handle", "verb", "furniture"),
    "treat": ("treat", "verb", "furniture"),
    "deal": ("deal", "verb", "furniture"),
    "cope": ("cope", "verb", "furniture"),
    "survive": ("survive", "verb", "furniture"),
    "endure": ("endure", "verb", "furniture"),
    "last": ("last", "verb", "furniture"),
    "continue": ("continue", "verb", "furniture"),
    "persist": ("persist", "verb", "furniture"),
    "maintain": ("maintain", "verb", "furniture"),
    "keep": ("keep", "verb", "furniture"),
    "hold": ("hold", "verb", "furniture"),
    "retain": ("retain", "verb", "furniture"),
    "preserve": ("preserve", "verb", "furniture"),
    "conserve": ("conserve", "verb", "furniture"),
    "stock": ("stock", "verb", "furniture"),
    "hoard": ("hoard", "verb", "furniture"),
    "collect": ("collect", "verb", "furniture"),
    "gather": ("gather", "verb", "furniture"),
    "accumulate": ("accumulate", "verb", "furniture"),
    "amass": ("amass", "verb", "furniture"),
    "heap": ("heap", "verb", "furniture"),
    "pile": ("pile", "verb", "furniture"),
    "stack": ("stack", "verb", "furniture"),
    "arrange": ("arrange", "verb", "furniture"),
    "organize": ("organize", "verb", "furniture"),
    "sort": ("sort", "verb", "furniture"),
    "classify": ("classify", "verb", "furniture"),
    "categorize": ("categorize", "verb", "furniture"),
    "group": ("group", "verb", "furniture"),
    "separate": ("separate", "verb", "furniture"),
    "divide": ("divide", "verb", "furniture"),
    "part": ("part", "verb", "furniture"),
    "join": ("join", "verb", "furniture"),
    "unite": ("unite", "verb", "furniture"),
    "combine": ("combine", "verb", "furniture"),
    "merge": ("merge", "verb", "furniture"),
    "blend": ("blend", "verb", "furniture"),
    "mix": ("mix", "verb", "furniture"),
    "mingle": ("mingle", "verb", "furniture"),
    "associate": ("associate", "verb", "furniture"),
    "connect": ("connect", "verb", "furniture"),
    "link": ("link", "verb", "furniture"),
    "attach": ("attach", "verb", "furniture"),
    "detach": ("detach", "verb", "furniture"),
    "disconnect": ("disconnect", "verb", "furniture"),
    "sever": ("sever", "verb", "furniture"),
    "shred": ("shred", "verb", "furniture"),
    "fragment": ("fragment", "verb", "furniture"),
    "scatter": ("scatter", "verb", "furniture"),
    "disperse": ("disperse", "verb", "furniture"),
    "distribute": ("distribute", "verb", "furniture"),
    "spread": ("spread", "verb", "furniture"),
    "broadcast": ("broadcast", "verb", "furniture"),
    "transmit": ("transmit", "verb", "furniture"),
    "send": ("send", "verb", "furniture"),
    "receive": ("receive", "verb", "furniture"),
    "accept": ("accept", "verb", "furniture"),
    "reject": ("reject", "verb", "furniture"),
    "refuse": ("refuse", "verb", "furniture"),
    "deny": ("deny", "verb", "furniture"),
    "admit": ("admit", "verb", "furniture"),
    "confess": ("confess", "verb", "furniture"),
    "disclose": ("disclose", "verb", "furniture"),
    "divulge": ("divulge", "verb", "furniture"),
    "tell": ("tell", "verb", "furniture"),
    "inform": ("inform", "verb", "furniture"),
    "notify": ("notify", "verb", "furniture"),
    "alert": ("alert", "verb", "furniture"),
    "warn": ("warn", "verb", "furniture"),
    "caution": ("caution", "verb", "furniture"),
    "advise": ("advise", "verb", "furniture"),
    "recommend": ("recommend", "verb", "furniture"),
    "suggest": ("suggest", "verb", "furniture"),
    "propose": ("propose", "verb", "furniture"),
    "offer": ("offer", "verb", "furniture"),
    "give": ("give", "verb", "furniture"),
    "donate": ("donate", "verb", "furniture"),
    "contribute": ("contribute", "verb", "furniture"),
    "supply": ("supply", "verb", "furniture"),
    "provide": ("provide", "verb", "furniture"),
    "furnish": ("furnish", "verb", "furniture"),
    "equip": ("equip", "verb", "furniture"),
    "prepare": ("prepare", "verb", "furniture"),
    "plan": ("plan", "verb", "furniture"),
    "design": ("design", "verb", "furniture"),
    "invent": ("invent", "verb", "furniture"),
    "innovate": ("innovate", "verb", "furniture"),
    "develop": ("develop", "verb", "furniture"),
    "improve": ("improve", "verb", "furniture"),
    "enhance": ("enhance", "verb", "furniture"),
    "upgrade": ("upgrade", "verb", "furniture"),
    "update": ("update", "verb", "furniture"),
    "modernize": ("modernize", "verb", "furniture"),
    "renew": ("renew", "verb", "furniture"),
    "restore": ("restore", "verb", "furniture"),
    "repair": ("repair", "verb", "furniture"),
    "fix": ("fix", "verb", "furniture"),
    "mend": ("mend", "verb", "furniture"),
    "patch": ("patch", "verb", "furniture"),
    "sew": ("sew", "verb", "furniture"),
    "stitch": ("stitch", "verb", "furniture"),
    "knit": ("knit", "verb", "furniture"),
    "weave": ("weave", "verb", "furniture"),
    "twist": ("twist", "verb", "furniture"),
    "braid": ("braid", "verb", "furniture"),
    "plait": ("plait", "verb", "furniture"),
    "bind": ("bind", "verb", "furniture"),
    "bar": ("bar", "verb", "furniture"),
    "hinder": ("hinder", "verb", "furniture"),
    "impede": ("impede", "verb", "furniture"),
    "delay": ("delay", "verb", "furniture"),
    "postpone": ("postpone", "verb", "furniture"),
    "defer": ("defer", "verb", "furniture"),
    "wait": ("wait", "verb", "furniture"),
    "rest": ("rest", "verb", "furniture"),
    "relax": ("relax", "verb", "furniture"),
    "unwind": ("unwind", "verb", "furniture"),
    "chill": ("chill", "verb", "furniture"),
    "calm": ("calm", "verb", "furniture"),
    "soothe": ("soothe", "verb", "furniture"),
    "comfort": ("comfort", "verb", "furniture"),
    "console": ("console", "verb", "furniture"),
    "reassure": ("reassure", "verb", "furniture"),
    "encourage": ("encourage", "verb", "furniture"),
    "motivate": ("motivate", "verb", "furniture"),
    "inspire": ("inspire", "verb", "furniture"),
    "stimulate": ("stimulate", "verb", "furniture"),
    "excite": ("excite", "verb", "furniture"),
    "thrill": ("thrill", "verb", "furniture"),
    "delight": ("delight", "verb", "furniture"),
    "please": ("please", "verb", "furniture"),
    "satisfy": ("satisfy", "verb", "furniture"),
    "content": ("content", "verb", "furniture"),
    "appease": ("appease", "verb", "furniture"),
    "placate": ("placate", "verb", "furniture"),
    "pacify": ("pacify", "verb", "furniture"),
    "mollify": ("mollify", "verb", "furniture"),
    "propitiate": ("propitiate", "verb", "furniture"),
    "atone": ("atone", "verb", "furniture"),
    "expiate": ("expiate", "verb", "furniture"),
    "redeem": ("redeem", "verb", "furniture"),
    "rescue": ("rescue", "verb", "furniture"),
    "deliver": ("deliver", "verb", "furniture"),
    "free": ("free", "verb", "furniture"),
    "liberate": ("liberate", "verb", "furniture"),
    "discharge": ("discharge", "verb", "furniture"),
    "dismiss": ("dismiss", "verb", "furniture"),
    "fire": ("fire", "verb", "furniture"),
    "sack": ("sack", "verb", "furniture"),
    "let": ("let", "verb", "furniture"),
    "leave": ("leave", "verb", "furniture"),
    "exit": ("exit", "verb", "furniture"),
    "quit": ("quit", "verb", "furniture"),
    "resign": ("resign", "verb", "furniture"),
    "retire": ("retire", "verb", "furniture"),
    "withdraw": ("withdraw", "verb", "furniture"),
    "retreat": ("retreat", "verb", "furniture"),
    "flee": ("flee", "verb", "furniture"),
    "escape": ("escape", "verb", "furniture"),
    "evade": ("evade", "verb", "furniture"),
    "dodge": ("dodge", "verb", "furniture"),
    "avoid": ("avoid", "verb", "furniture"),
    "shun": ("shun", "verb", "furniture"),
    "ignore": ("ignore", "verb", "furniture"),
    "neglect": ("neglect", "verb", "furniture"),
    "disregard": ("disregard", "verb", "furniture"),
    "overlook": ("overlook", "verb", "furniture"),
    "forget": ("forget", "verb", "furniture"),
    "remember": ("remember", "verb", "furniture"),
    "recall": ("recall", "verb", "furniture"),
    "recollect": ("recollect", "verb", "furniture"),
    "remind": ("remind", "verb", "furniture"),
    "hint": ("hint", "verb", "furniture"),
    "imply": ("imply", "verb", "furniture"),
    "mean": ("mean", "verb", "furniture"),
    "signify": ("signify", "verb", "furniture"),
    "indicate": ("indicate", "verb", "furniture"),
    "show": ("show", "verb", "furniture"),
    "demonstrate": ("demonstrate", "verb", "furniture"),
    "exhibit": ("exhibit", "verb", "furniture"),
    "present": ("present", "verb", "furniture"),
    "introduce": ("introduce", "verb", "furniture"),
    "announce": ("announce", "verb", "furniture"),
    "declare": ("declare", "verb", "furniture"),
    "state": ("state", "verb", "furniture"),
    "assert": ("assert", "verb", "furniture"),
    "claim": ("claim", "verb", "furniture"),
    "argue": ("argue", "verb", "furniture"),
    "debate": ("debate", "verb", "furniture"),
    "discuss": ("discuss", "verb", "furniture"),
    "converse": ("converse", "verb", "furniture"),
    "talk": ("talk", "verb", "furniture"),
    "speak": ("speak", "verb", "furniture"),
    "say": ("say", "verb", "furniture"),
    "mention": ("mention", "verb", "furniture"),
    "refer": ("refer", "verb", "furniture"),
    "cite": ("cite", "verb", "furniture"),
    "quote": ("quote", "verb", "furniture"),
    "paraphrase": ("paraphrase", "verb", "furniture"),
    "translate": ("translate", "verb", "furniture"),
    "interpret": ("interpret", "verb", "furniture"),
    "explain": ("explain", "verb", "furniture"),
    "clarify": ("clarify", "verb", "furniture"),
    "elucidate": ("elucidate", "verb", "furniture"),
    "illuminate": ("illuminate", "verb", "furniture"),
    "gleam": ("gleam", "verb", "furniture"),
    "glint": ("glint", "verb", "furniture"),
    "sparkle": ("sparkle", "verb", "furniture"),
    "twinkle": ("twinkle", "verb", "furniture"),
    "flicker": ("flicker", "verb", "furniture"),
    "wink": ("wink", "verb", "furniture"),
    "squint": ("squint", "verb", "furniture"),
    "stare": ("stare", "verb", "furniture"),
    "gaze": ("gaze", "verb", "furniture"),
    "glare": ("glare", "verb", "furniture"),
    "peek": ("peek", "verb", "furniture"),
    "peer": ("peer", "verb", "furniture"),
    "glimpse": ("glimpse", "verb", "furniture"),
    "spot": ("spot", "verb", "furniture"),
    "detect": ("detect", "verb", "furniture"),
    "locate": ("locate", "verb", "furniture"),
    "seek": ("seek", "verb", "furniture"),
    "hunt": ("hunt", "verb", "furniture"),
    "chase": ("chase", "verb", "furniture"),
    "pursue": ("pursue", "verb", "furniture"),
    "track": ("track", "verb", "furniture"),
    "trail": ("trail", "verb", "furniture"),
    "shadow": ("shadow", "verb", "furniture"),
    "stalk": ("stalk", "verb", "furniture"),
    "shield": ("shield", "verb", "furniture"),
    "shelter": ("shelter", "verb", "furniture"),
    "harbor": ("harbor", "verb", "furniture"),
    "accommodate": ("accommodate", "verb", "furniture"),
    "lodge": ("lodge", "verb", "furniture"),
    "quarter": ("quarter", "verb", "furniture"),
    "position": ("position", "verb", "furniture"),
    "place": ("place", "verb", "furniture"),
    "set": ("set", "verb", "furniture"),
    "put": ("put", "verb", "furniture"),
    "install": ("install", "verb", "furniture"),
    "establish": ("establish", "verb", "furniture"),
    "found": ("found", "verb", "furniture"),
    "institute": ("institute", "verb", "furniture"),
    "order": ("order", "verb", "furniture"),
    "line": ("line", "verb", "furniture"),
    "rank": ("rank", "verb", "furniture"),
    "rate": ("rate", "verb", "furniture"),
    "score": ("score", "verb", "furniture"),
    "check": ("check", "verb", "furniture"),
    "verify": ("verify", "verb", "furniture"),
    "confirm": ("confirm", "verb", "furniture"),
    "validate": ("validate", "verb", "furniture"),
    "prove": ("prove", "verb", "furniture"),
    "acknowledge": ("acknowledge", "verb", "furniture"),
    "recognize": ("recognize", "verb", "furniture"),
    "identify": ("identify", "verb", "furniture"),
    "term": ("term", "verb", "furniture"),
    "brand": ("brand", "verb", "furniture"),
    "stamp": ("stamp", "verb", "furniture"),
    "imprint": ("imprint", "verb", "furniture"),
    "engrave": ("engrave", "verb", "furniture"),
    "etch": ("etch", "verb", "furniture"),
    "inscribe": ("inscribe", "verb", "furniture"),
    "write": ("write", "verb", "furniture"),
    "record": ("record", "verb", "furniture"),
    "log": ("log", "verb", "furniture"),
    "register": ("register", "verb", "furniture"),
    "enroll": ("enroll", "verb", "furniture"),
    "sign": ("sign", "verb", "furniture"),
    "contract": ("contract", "verb", "furniture"),
    "agree": ("agree", "verb", "furniture"),
    "consent": ("consent", "verb", "furniture"),
    "approve": ("approve", "verb", "furniture"),
    "authorize": ("authorize", "verb", "furniture"),
    "permit": ("permit", "verb", "furniture"),
    "allow": ("allow", "verb", "furniture"),
    "enable": ("enable", "verb", "furniture"),
    "empower": ("empower", "verb", "furniture"),
    "license": ("license", "verb", "furniture"),
    "certify": ("certify", "verb", "furniture"),
    "accredit": ("accredit", "verb", "furniture"),
    "endorse": ("endorse", "verb", "furniture"),
    "sponsor": ("sponsor", "verb", "furniture"),
    "support": ("support", "verb", "furniture"),
    "finance": ("finance", "verb", "furniture"),
    "fund": ("fund", "verb", "furniture"),
    "subsidize": ("subsidize", "verb", "furniture"),
    "invest": ("invest", "verb", "furniture"),
    "spend": ("spend", "verb", "furniture"),
    "expend": ("expend", "verb", "furniture"),
    "use": ("use", "verb", "furniture"),
    "employ": ("employ", "verb", "furniture"),
    "utilize": ("utilize", "verb", "furniture"),
    "apply": ("apply", "verb", "furniture"),
    "exercise": ("exercise", "verb", "furniture"),
    "practice": ("practice", "verb", "furniture"),
    "perform": ("perform", "verb", "furniture"),
    "act": ("act", "verb", "furniture"),
    "do": ("do", "verb", "furniture"),
    "produce": ("produce", "verb", "furniture"),
    "generate": ("generate", "verb", "furniture"),
    "yield": ("yield", "verb", "furniture"),
    "bear": ("bear", "verb", "furniture"),
    "carry": ("carry", "verb", "furniture"),
    "transport": ("transport", "verb", "furniture"),
    "convey": ("convey", "verb", "furniture"),
    "transfer": ("transfer", "verb", "furniture"),
    "shift": ("shift", "verb", "furniture"),
    "relocate": ("relocate", "verb", "furniture"),
    "displace": ("displace", "verb", "furniture"),
    "replace": ("replace", "verb", "furniture"),
    "substitute": ("substitute", "verb", "furniture"),
    "exchange": ("exchange", "verb", "furniture"),
    "swap": ("swap", "verb", "furniture"),
    "trade": ("trade", "verb", "furniture"),
    "buy": ("buy", "verb", "furniture"),
    "purchase": ("purchase", "verb", "furniture"),
    "acquire": ("acquire", "verb", "furniture"),
    "obtain": ("obtain", "verb", "furniture"),
    "get": ("get", "verb", "furniture"),
    "harvest": ("harvest", "verb", "furniture"),
    "reap": ("reap", "verb", "furniture"),
    "pick": ("pick", "verb", "furniture"),
    "select": ("select", "verb", "furniture"),
    "choose": ("choose", "verb", "furniture"),
    "elect": ("elect", "verb", "furniture"),
    "vote": ("vote", "verb", "furniture"),
    "nominate": ("nominate", "verb", "furniture"),
    "appoint": ("appoint", "verb", "furniture"),
    "assign": ("assign", "verb", "furniture"),
    "allocate": ("allocate", "verb", "furniture"),
    "partition": ("partition", "verb", "furniture"),
    "segment": ("segment", "verb", "furniture"),
    "section": ("section", "verb", "furniture"),
}


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load JSONL file."""
    data = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                data.append(json.loads(line))
    return data


def build_dict_index(dict_data: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Build index of existing dictionary entries by zolai word."""
    index = {}
    for entry in dict_data:
        word = entry.get("zolai", "").strip().lower()
        if word and word not in index:
            index[word] = entry
    return index


def infer_pos(word: str) -> str:
    """Infer part of speech from word structure."""
    if word in PARTICLES or len(word) <= 2:
        return "particle"
    if word.endswith(("na", "tak", "ziau")):
        return "noun"
    if word.endswith(("hi", "ta", "zo", "ding", "khin", "lai")):
        return "verb"
    if word.endswith(("am", "ah", "aw")):
        return "adverb"
    if re.search("(ci|ngai|leh|tua)", word):
        return "conjunction"
    if word in VERB_ROOTS:
        return "verb"
    if word in NOUN_ROOTS:
        return "noun"
    return "noun"


def infer_category(word: str) -> str:
    """Infer word category from morphological analysis."""
    if word in PARTICLES:
        return "grammar"
    if word.endswith(("na", "tak")):
        return "abstract"
    if word.endswith(("tung", "lei", "gam")):
        return "nature"
    if word.endswith(("pih", "kam")):
        return "communication"
    return "general"


def morphological_inference(word: str, freq: int) -> dict[str, Any]:
    """Infer meaning through morphological analysis."""
    if word in KNOWN_TRANSLATIONS:
        en, pos, cat = KNOWN_TRANSLATIONS[word]
        return {
            "zo": word,
            "en": en,
            "freq": freq,
            "source": "zomidaily",
            "pos": pos,
            "category": cat,
        }
    for root, meaning in VERB_ROOTS.items():
        if word.startswith(root) and len(word) > len(root):
            suffix = word[len(root) :]
            if suffix in ("hi", "ta", "zo", "ding", "in", "hi"):
                return {
                    "zo": word,
                    "en": f"{meaning} (inflected)",
                    "freq": freq,
                    "source": "zomidaily",
                    "pos": "verb",
                    "category": "general",
                }
            return {
                "zo": word,
                "en": f"{meaning}-related",
                "freq": freq,
                "source": "zomidaily",
                "pos": "verb",
                "category": "general",
            }
    for root, meaning in NOUN_ROOTS.items():
        if word.startswith(root) and len(word) > len(root):
            suffix = word[len(root) :]
            if suffix in ("na", "tak", "ziau", "pih"):
                return {
                    "zo": word,
                    "en": f"{meaning} (derived)",
                    "freq": freq,
                    "source": "zomidaily",
                    "pos": "noun",
                    "category": "general",
                }
    for root, meaning in ADJ_ROOTS.items():
        if word.startswith(root) and len(word) > len(root):
            return {
                "zo": word,
                "en": f"{meaning} (adjective)",
                "freq": freq,
                "source": "zomidaily",
                "pos": "adjective",
                "category": "general",
            }
    if word in PARTICLES:
        return {
            "zo": word,
            "en": "[function word]",
            "freq": freq,
            "source": "zomidaily",
            "pos": "particle",
            "category": "grammar",
        }
    if re.search("(tion|ment|ness|ful|less|able|ous|ive)", word):
        return {
            "zo": word,
            "en": f"[loan word: {word}]",
            "freq": freq,
            "source": "zomidaily",
            "pos": "noun",
            "category": "loanword",
        }
    pos = infer_pos(word)
    cat = infer_category(word)
    return {
        "zo": word,
        "en": "[to be translated]",
        "freq": freq,
        "source": "zomidaily",
        "pos": pos,
        "category": cat,
    }


def build_expanded_dict(top_n: int = 1000) -> None:
    """Build expanded dictionary from zomidaily new words."""
    new_words = load_jsonl(NEW_WORDS_PATH)
    master_dict = load_jsonl(MASTER_DICT_PATH)
    dict_index = build_dict_index(master_dict)
    print(f"Loaded {len(new_words)} new words from zomidaily")
    print(f"Loaded {len(master_dict)} entries from master dictionary")
    top_words = sorted(new_words, key=lambda x: x.get("count", 0), reverse=True)[:top_n]
    print(f"\nProcessing top {len(top_words)} words...")
    expanded = []
    skipped = 0
    translated = 0
    inferred = 0
    for entry in top_words:
        word = entry.get("word", "").strip().lower()
        freq = entry.get("count", 0)
        if not word or len(word) < 2:
            skipped += 1
            continue
        if word in dict_index:
            existing = dict_index[word]
            en = existing.get("english_clean", "")
            if en and en != "[to be translated]":
                expanded.append(
                    {
                        "zo": word,
                        "en": en,
                        "freq": freq,
                        "source": "zomidaily+dict",
                        "pos": "noun",
                        "category": "from_dictionary",
                    }
                )
                translated += 1
                continue
        result = morphological_inference(word, freq)
        if result["en"] != "[to be translated]":
            inferred += 1
        expanded.append(result)
    expanded.sort(key=lambda x: x.get("freq", 0), reverse=True)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        for entry in expanded:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print("\nResults:")
    print(f"  Total words processed: {len(expanded)}")
    print(f"  Skipped (too short): {skipped}")
    print(f"  From existing dictionary: {translated}")
    print(f"  Morphologically inferred: {inferred}")
    print(f"  Needing review: {len(expanded) - translated - inferred}")
    print(f"\nOutput written to: {OUTPUT_PATH}")


if __name__ == "__main__":
    build_expanded_dict(top_n=1000)
